version: 1.0.{build}

image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  webapp1_folder: .\AppVeyorAzureTest
  webapp1_proj: $(webapp1_folder)\AppVeyorAzureTest.csproj
  webapp1_package: AppVeyorAzureTest.$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)
  test_proj: .\XUnitSample.Test\XUnitSample.Test.csproj


before_build:
  - ps: .\before_build.ps1
  
build:
  verbosity: minimal
  project: AppVeyorAzureTest.sln

after_build:
  - ps: .\package.ps1 -projectPath $env:webapp1_proj -packageName $env:webapp1_package -absoluteRepoDirectory $env:APPVEYOR_BUILD_FOLDER

artifacts:
- path: '**\$(webapp1_package).zip'

# automatic test detection not supported in dotnet core xUnit
# turn it off and run custom test script instead
test: off
test_script:
  - ps: .\test_script.ps1 $env:test_proj

deploy:
  - provider: WebDeploy
    name: Production
    server: https://$(azure_website).scm.azurewebsites.net:443/msdeploy.axd?site=$(azure_website)
    website: $(azure_website)
    username: $(azure_username)
    password: $(azure_password)
    artifact: $(webapp1_package).zip
    aspnet_core: true
    aspnet_core_force_restart: true
    app_offline: true
    remove_files: true
    do_not_use_checksum: true
    on:
      branch: master