version: 1.0.{build}

image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  webapp1_folder: .\AppVeyorAzureTest
  webapp1_proj: $(webapp1_folder)\AppVeyorAzureTest.csproj
  webapp1_package: AppVeyorAzureTest.$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)


before_build:
  - cmd: before_build.cmd %webapp1_folder% %APPVEYOR_BUILD_FOLDER%
  
build:
  verbosity: minimal
  project: AppVeyorAzureTest.sln

after_build:
  - ps: .\package.ps1 -projectPath $env:webapp1_proj -packageName $env:webapp1_package -absoluteRepoDirectory $env:APPVEYOR_BUILD_FOLDER

artifacts:
- path: '**\$(webapp1_package).zip'

deploy:
  - provider: WebDeploy
    name: Production
    server: https://$(azure_website).scm.azurewebsites.net:443/msdeploy.axd?site=$(azure_website)
    website: $(azure_website)
    username: $(azure_username)
    password:
      secure: $(azure_password)
    artifact: $(webapp1_package).zip
    aspnet_core: true
    aspnet_core_force_restart: true
    app_offline: true
    remove_files: true
    do_not_use_checksum: true
    on:
      branch: master