version: 1.0.{build}

image: Visual Studio 2017
configuration: Release
platform: Any CPU

build:
  verbosity: minimal
  project: AppVeyorAzureTest.sln
  
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  webapp1_folder: .\AppVeyorAzureTest
  webapp1_proj: $(webapp1_folder)\AppVeyorAzureTest.csproj
  webapp1_package: AppVeyorAzureTest.$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)


before_build:
  - cmd: before_build.cmd